version: '2'

services:
  test:
    image: node:8-alpine@sha256:c9f2470464363addb0be6a61678f44854e73eee974bbc792a71d4d2b7ffd5edd
    depends_on:
      - db
    volumes:  
      - ./:/build
    working_dir: /build
    entrypoint:
      - /bin/sh
      - "-c"
      - "npm install && npm run test:coverage"      
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@db/postgres 
  
  db:
    image: postgres:9.6@sha256:9d8deca17591f6fef6b2c338fee1a5d7c96da99f18bd51149440099239085800
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres