version: '2'

services:
  test:
    image: node:8-alpine
    depends_on:
      - db
    volumes:  
      - ./:/build
    working_dir: /build
    entrypoint:
      - /bin/sh
      - "-c"
      - "npm install && npm run test:coverage"      
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@db/postgres 
  
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres