version: '2'

services:
  db:
    image: postgres:9.6@sha256:e7684004cf3f064a56b7a2bb35d858ae3226ff12ecf9385828ea4128bb065a98
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres