version: '2'

services:
  test:
    image: node:8-alpine@sha256:d3ecde67a30db99d10a32173cc2fee8766bb42430feb2f819179c8dcf494dac1
    depends_on:
      - db
    volumes:  
      - ./:/build
    working_dir: /build
    entrypoint:
      - /bin/sh
      - "-c"
      - "npm install && npm run test:coverage"      
    environment:
      PG_CONNECTION_STRING: postgres://postgres:postgres@db/postgres 
  
  db:
    image: postgres:9.6@sha256:111954515f3781cf0efb3cdbb0120f0d5bbfd3244b80104b3e901e2289ae5c7b
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres