version: '2'

services:
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres